GET http://localhost:5000/posts
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9tIiwiaWF0IjoxNzM0OTYwODMxLCJleHAiOjE3MzQ5NjA4NDZ9.awL2mbUUcB3GLgylJZQwqHUyDyuZrV4mpo9Oshn53kY


###

POST http://localhost:4000/token
Content-Type: application/json

{
   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9tIiwiaWF0IjoxNzM0OTYwODMxfQ.OtOEaJ0m6fZxykwIGxNVrJXKnnmWOEjO9HnZJi8rrsM"
}


###

POST http://localhost:4000/login
Content-Type: application/json

{
   "username": "Tom"
}